version: "3.8"

services:
  backend:
    build:
      context: backend
      dockerfile: backend/Dockerfile
    ports:
      - "8100:8100"
    volumes:
      - ./backend:/app      
    depends_on:
      - mongo         

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
